version: '3'
services:
  ohm_tiles_coverage:
    image: ohm/ohm_tiles_coverage:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - AWS_PROFILE=ohm
    volumes:
        - ./:/mnt
        - ~/.aws/credentials:/root/.aws/credentials:ro
    working_dir: /mnt
